---
title: "viz_i"
subtitle: "part II"
date: "3/14/2022"
output: github_document
---


```{r}
library(tidyverse)
library(patchwork)
```

## Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather_df
```


## Remember this plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5)
```

# Labels
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(c)", 
    y = "Maximum daily temperature(c)",
    caption = "Data from rnoaa package, temperature in 2017
    "
  )
```

## Scales
Start with the same plot

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(c)", 
    y = "Maximum daily temperature(c)",
    caption = "Data from rnoaa package, temperature in 2017
    "
  ) +
  scale_x_continuous(
    breaks = c(-15, 0, 15), 
    labels = c("-15 C", "0" , "15")
  ) +
  scale_y_continuous(
    position = "right"
  )
```

Look at color scales
```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(c)", 
    y = "Maximum daily temperature(c)",
    caption = "Data from rnoaa package, temperature in 2017
    "
  ) +
  scale_color_hue(
    name = "Location",
    h = c(100, 300)
  )
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(c)", 
    y = "Maximum daily temperature(c)",
    caption = "Data from rnoaa package, temperature in 2017
    "
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE)
  
```

## Themes

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(c)", 
    y = "Maximum daily temperature(c)",
    caption = "Data from rnoaa package, temperature in 2017
    "
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) +
  theme(legend.position = "bottom")
```

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  labs(
    title = "Temperature plot",
    x = "Minimum daily temperature(c)", 
    y = "Maximum daily temperature(c)",
    caption = "Data from rnoaa package, temperature in 2017
    "
  ) +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE) +
  ggthemes::theme_economist()
```


## Setting options
```{r, eval = FALSE}
library(tidyverse)

kniter::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90"
)

theme_set(theme. minimal() + theme(lengend. position = "bottom"))

options(
   ggplot2.continuous.colour = "viridis" ,
   ggplot2.continuous. fill = "viridis"
)

scale_colour_discrete = scale_color_vifidis_d
scale_fill_discrete = scale_fill_viridis_d

```

## Data args in `geom`

```{r}
central_park = 
  weather_df %>% 
  filter(name == "CentralPark_NY")

waikiki =
  weather_df %>% 
  filter(name == "Waikiki_HA")

ggplot(data = waikiki, aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_line(data = central_park)
  
```


## patchwork
Remember faceting 

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .5) +
  facet_grid(. ~name)
```

what happens when you want to multipanel plots but can't facet?
```{r}
tmax_tmin_p=
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .5) +
  theme(legend.position = "none")

precp_dens_p=
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")

tmax_date_p=
  weather_df %>% 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  theme(legend.position = "none")

tmax_tmin_p + (precp_dens_p + tmax_date_p)
```

##Data manipulation

Control your factors. 

```{r}
weather_df %>% 
  mutate(
    name = factor(name),
    name = forcats::fct_relevel(name, c("Wakiki_HA"))
) %>% 
  ggplot(aes(x = name, y = tmax, fill = name)) +
  geom_violin(alpha = .5)
  
  
```

What if i wanted densitites for tmin and tmax simultaneously?
```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  pivot_longer(
    tmax:tmin,
    names_to = "observation", 
    values_to = "temperatures"
  ) %>% 
  ggplot(aes(x = temperatures, fill = observation)) +
  geom_density(alpha = .5)
```

